### ISSUE TITLE
Can't return pandas dataframes from cloudknotted functions?

### ISSUE THREAD

**Issue by arokem** [nrdg/cloudknot#138]
When running a function that had something like: 

```
def func(input):
    # ... computing stuff
    return pd.read_csv('file_that_was_created.csv')

```

We ran into the following error:

```
ValueError                                Traceback (most recent call last)
<ipython-input-22-596134ca4719> in <module>()
      1 r0 = results[0]
----> 2 r0.result()

/usr/local/lib/python2.7/dist-packages/concurrent/futures/_base.pyc in result(self, timeout)
    453                 raise CancelledError()
    454             elif self._state == FINISHED:
--> 455                 return self.__get_result()
    456 
    457             self._condition.wait(timeout)

/usr/local/lib/python2.7/dist-packages/concurrent/futures/thread.pyc in run(self)
     61 
     62         try:
---> 63             result = self.fn(*self.args, **self.kwargs)
     64         except:
     65             e, tb = sys.exc_info()[1:]

/usr/local/lib/python2.7/dist-packages/cloudknot-0.3.dev0-py2.7.egg/cloudknot/cloudknot.pyc in <lambda>(j)
   1568 
   1569         executor = ThreadPoolExecutor(min(len(these_jobs), max_threads))
-> 1570         futures = [executor.submit(lambda j: j.result(), jb)
   1571                    for jb in these_jobs]
   1572 

/usr/local/lib/python2.7/dist-packages/cloudknot-0.3.dev0-py2.7.egg/cloudknot/aws/batch.pyc in result(self, timeout)
   1839 
   1840             response = clients['s3'].get_object(Bucket=bucket, Key=key)
-> 1841             return pickle.loads(response.get('Body').read())
   1842 
   1843     def terminate(self, reason):

/usr/lib/python2.7/pickle.pyc in loads(str)
   1386 def loads(str):
   1387     file = StringIO(str)
-> 1388     return Unpickler(file).load()
   1389 
   1390 # Doctest

/usr/lib/python2.7/pickle.pyc in load(self)
    862             while 1:
    863                 key = read(1)
--> 864                 dispatch[key](self)
    865         except _Stop, stopinst:
    866             return stopinst.value

/usr/lib/python2.7/pickle.pyc in load_proto(self)
    890         proto = ord(self.read(1))
    891         if not 0 <= proto <= 2:
--> 892             raise ValueError, "unsupported pickle protocol: %d" % proto
    893     dispatch[PROTO] = load_proto
    894 

ValueError: unsupported pickle protocol: 4
```

Does this mean we can't return data-frames from within cloudknotted functions?

**Comment by richford** [comment]
Can you point me to the S3 bucket that this result is in? I'd like to play around with it a bit to find the best way to fix this. We can always have use `pd.read_pickle` and `df.to_pickle()` if isinstance(result, pd.DataFrame)` but I'd prefer not to have to check the type of the output.

**Comment by richford** [comment]
Aha, "Pickle protocol version 4 was added in Python 3.4" from the [docs here](https://docs.python.org/3/library/pickle.html#data-stream-format). You're using 2.7, correct? So perhaps for 2.7 we need to specify a lower protocol.

**Comment by richford** [comment]
`cloudpickle` uses `pickle.HIGHEST_PROTOCOL` by default. So I think what's happening here is that the EC2 or spot instance has a higher `pickle.HIGHEST_PROTOCOL` than your local machine (either your actual local machine or the one you're using on AWS).

Maybe we can pass `pickle_protocol` as an input to the python script to require that the EC2 instance uses a pickle protocol that the "local" machine can use.

**Comment by richford** [comment]
@arokem, can you confirm that this is a problem with coordinating pickle protocol between the machines on batch and the machine running cloudknot? (i.e. not something that is unique to pandas DataFrames?)

**Comment by richford** [comment]
But wait, the docker base image should have the same version of python as the one running cloudknot, right? Does your docker image's base image match your python version?

**Comment by arokem** [comment]
Because we're driving cloudknot from an AWS machine, we're using different versions for the driver (python 2.7) and the workers (python 3.6), so we used a pre-specified base image. 

We'll try pickling something else next week, and get back to you on this.

**Comment by richford** [comment]
@arokem, any updates on this issue? Did you try pickling other objects?

**Comment by arokem** [comment]
Have not tried anything yet. Sorry about the slowness.
