### ISSUE TITLE
Specifying bid_percentage doesn't seem to launch spot instances

### ISSUE THREAD

**Issue by arokem** [nrdg/cloudknot#140]
I know this worked before, but now doesn't seem to be working for us. 

Setting `bid_percentage=25` as input, but no spot requests get generated and `aws ec2 describe-spot-instance-requests` returns empty.

**Comment by richford** [comment]
For now, try also specifying `resource_type='SPOT'`. But we should probably make it so that specifying a bid percentage automatically changes the resource type to SPOT. Having the two different parameters seems redundant to me. I actually thought I already did this, but apparently not.

**Comment by arokem** [comment]
Aha! Thanks!
