### ISSUE TITLE
Improve resource tagging

### ISSUE THREAD

**Issue by richford** [nrdg/cloudknot#248]
- [ ] Allow user to override the default tags by passing a tag dict to `ck.Knot()`
- [ ] Require a "Project" tag

These two could be combined with a `tag` keyword arg. If it's a string, we assume it's the value for the "Project" tag. If it's a dict, we assume it's the tag dict and require the "Project" key, treating additional keys as additional tags and incorporating the default tags if they are missing.

**Comment by arokem** [comment]
I don't know if I would make the "project" tag **required** (except in our specific context). Some users might not need this at all?
