### ISSUE TITLE
define python version or virtualenv

### ISSUE THREAD

**Issue by DrJohnDale** [nrdg/cloudknot#285]
Hi

Is there a way to define which python version or command is used?
e.g. launch with python3.8 instead of python?

Also is there a way to tell it to use a virtualenv inside the image?

**Comment by arokem** [comment]
Thanks for getting in touch. Let me see if I can help: regarding use of a specific version of Python, you can inherit the docker image that is used to generate the cloudknot docker image from any image that you would like. Check out [this example](https://github.com/nrdg/cloudknot/blob/master/examples/04_using_dockerimage.ipynb). You'll see that in code cell 4, we set a key-word argument `base_image="python:3.7"`, which directs the image to be built inherting from the `3.7` tag of the [official python image](https://hub.docker.com/_/python).

Similarly, you can build your own docker image locally and build your CK image based on that image. This might help you from having to select a particular virtualenv inside the image (?).

**Comment by DrJohnDale** [comment]
Thanks for the answer.  I have done what you suggested and it works. 
The complexity for me came from needing to use an ubuntu 18 base image (we have some complex builds stuff) not a python base image and therefore need to change the command python from python 2 to python 3.
For anyone else who finds this and needs to use an ubuntu 18 base image I had to add the following to my docker image before doing any pip install to get it to work

```
# add python 3.8
RUN apt-get update && apt-get -y install software-properties-common
RUN add-apt-repository ppa:deadsnakes/ppa && \
    apt-get update && apt-get -y install python3.8 python3-pip python3.8-dev

RUN update-alternatives --install /usr/bin/python python /usr/bin/python3.8 1

#sort out pip
RUN cd /tmp && curl https://bootstrap.pypa.io/get-pip.py -o get-pip.py && python get-pip.py
```

**Comment by arokem** [comment]
Thanks! I moved this into a [discussion](https://github.com/nrdg/cloudknot/discussions/288), in case anyone wants to follow up. For now, I'll close this issue.
