### ISSUE TITLE
GPU spec always required?

### ISSUE THREAD

**Issue by arokem** [nrdg/cloudknot#301]
We're seeing creation of the knot stack fail on CloudFormation with "An error occurred (ClientException) when calling the RegisterJobDefinition operation: Error executing request, Exception : GPU in resourceRequirement must be at least 1, got 0., RequestId: 96454414-bd07-4bf3-ab2f-c869823a96bd" appearing for the JobDefinition event. Might be that #299 introduced a (too strict) requirement for GPUs?

**Comment by richford** [comment]
I believe I fixed this in [3c70a01](https://github.com/nrdg/cloudknot/commit/3c70a01bc89a861e7bf3182381c12c337df27ab5). Are you working off of GitHub or pypi? If pypi, perhaps this justifies a micro release.

**Comment by arokem** [comment]
Hmm. Still investigating -- might be that this is happening on another version -- not on master.

**Comment by arokem** [comment]
In particular, there's something odd happening with versions. When I install locally from master I get this: 

```
Installing collected packages: cloudknot
  Attempting uninstall: cloudknot
    Found existing installation: cloudknot 0.5.2
    Uninstalling cloudknot-0.5.2:
      Successfully uninstalled cloudknot-0.5.2
  Running setup.py develop for cloudknot
Successfully installed cloudknot-0.4.3.dev9663313222
```

Which suggests to me that something is wonky about versioning.

**Comment by arokem** [comment]
Oh - I see - I need to pull the tags down to have the right version string. That's a bit funky, but understandable.

**Comment by arokem** [comment]
OK - I do think that this is resolved on master and we just had some installation confusion. I think that a micro-version release would be a good idea, because this will stop other users on step 0. But closing this one.
