### ISSUE TITLE
Integrate with cottoncandy for I/O

### ISSUE THREAD

**Issue by arokem** [nrdg/cloudknot#73]
See: http://gallantlab.github.io/cottoncandy/

**Comment by richford** [comment]
I'm going through old issues and seeing if they are still needed. @arokem, do you think this is still needed? And could you tell me a bit about what you envision for this?

**Comment by arokem** [comment]
I *believe* that at the time I might have thought we would use this like we currently use s3fs. I still think it's nifty, but I think that we can close this.
